Fix type of coordinate system fields
fNIRS/snirf pull request #101
Opened 2022-01-31 05:20 UTC by rob-luke

Sorry @sstucker but I think the types were wrong in #94 
Please double-check my understanding of the string types is correct. But you would only have one string to specify the coordinate system per probe. As all sensors in the probe would use the same coordinate system.
Also, I had forgotten to add the fields to the table at the top.

2022-01-31 19:15 UTC, sstucker commented
Sorry for my haste!

You should also add the additions to [the table of contents at the top of the document](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#table-of-content).

2022-01-31 19:16 UTC, sstucker requested changes
Need to add the new fields to TOC from line 56

2022-02-01 23:14 UTC, rob-luke commented
Good catch, can you please review again @sstucker

2022-02-01 23:14 UTC, sstucker approved these changes

2022-02-01 23:18 UTC, merged