`aux/dataTimeSeries` can encode channels in the 2nd dimension
fNIRS/snirf pull request #116
Opened 2022-06-01 16:10 UTC by sstucker

Proposing this because of request #107 and because of the overhead of HDF5 groups in the Indexed Groups format defined by the SNIRF spec. (#103) 

The language describing the ndim of `aux/dataTimeSeries` was already ambiguous, suggesting a unit 2nd dimension was required (this is different than an array of ndim=1 in the HDF5 format, see #99). This change allows for "channels" in an aux `dataTimeSeries` with a caveat that 3-dimensional accelerometer sensors should still use individual aux blocks to be more backwards compatible.

We could also introduce a new `"ACCEL_XYZ"` name in the appendix. The current names are intended to mirror the BIDS nomenclature for the same data, see #81

2022-06-13 05:47 UTC, samuelpowell commented
Would a brief example help clarify that this is not intended to replace the use of `ACCEL_X`, `ACCEL_Y`, `ACCEL_Z`? Something like:

> If multiple channels of related data are generated by a system, they may be encoded in the second dimension of the time series. For example, a system containing more than one accelerometer may output this data as a set of `ACCEL_X`/`ACCEL_Y`/`ACCEL_Z` auxiliary time series, where each has the dimension of `<time points> x <no. accelerometer>`. Alternative uses of the channel data include storing complex numbers, ...

2022-06-13 16:48 UTC, sstucker commented
Yes, your example is more clear, I like it

2022-06-22 06:45 UTC, rob-luke requested changes
Other than a small typo this looks good to go

2022-06-22 06:45 UTC, rob-luke commented on snirf_specification.md
> +This is string describing the j<sup>th</sup> auxiliary data timecourse. While auxilliary data can be given any title, standard names for commonly used auxilliary channels (i.e. accelerometer data) ar
```suggestion
This is string describing the j<sup>th</sup> auxiliary data timecourse. While auxiliary data can be given any title, standard names for commonly used auxiliary channels (i.e. accelerometer data) are specified in the appendix.
```

2022-06-23 03:15 UTC, rob-luke approved these changes

2022-07-12 10:14 UTC, merged