Improve semantic versioning implementation
fNIRS/snirf pull request #147
Opened 2024-07-10 04:03 UTC by rob-luke

- Modified the release procedure to include roles from the governance doc (which was created after the release procedure).
- Modified the examples in the release procedure to be semantic version compliant.
- Removed the "v" from the document to create a compliant version 
- Added "development" to the development version in the doc
  - This also helps users understand if they are looking at a released or development version

2024-07-10 12:24 UTC, Horschig commented on RELEASE.md
> +4. Open a pull request that makes the following modifications:
[1...2...4](https://www.youtube.com/watch?v=xOrgLj9lOwk)

2024-07-10 12:24 UTC, Horschig commented on RELEASE.md
> +   1. Modify the version number in the opening lines of the specification to match the version to be released (e.g., `1.0.0`).
1!

Better a)?

2024-08-26 16:59 UTC, sstucker approved these changes

2025-01-02 22:31 UTC, dboas approved these changes
I addressed the two comments made by @Horschig 
The rest looks good to me

2025-01-03 08:53 UTC, samuelpowell requested changes
Current formatting does not render properly in Github Markdown (see [guidance](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#nested-lists)

2025-01-03 08:53 UTC, samuelpowell commented on RELEASE.md
> +   a. Modify the version number in the opening lines of the specification to match the version to be released (e.g., `1.0.0`).
Github is not parsing this markdown as a (sub-) bullet point, it appears inline in the preview text. Likely whitespace or numeral/character mix issue. This applies to all bullets below.

2025-01-03 08:59 UTC, samuelpowell commented
Does CHANGELOG also need updating @rob-luke ?

2025-01-07 20:56 UTC, dboas commented on RELEASE.md
> +   1. Modify the version number in the opening lines of the specification to match the version to be released (e.g., `1.0.0`).
a) doesn't work. But it looks good as is in github preview

2025-01-07 20:57 UTC, dboas approved these changes

2025-01-07 20:58 UTC, dboas commented
@samuelpowell I put it back the way it was. Github does a good job as is. I shouldn't have changed it in the first place, but should have looked at the MD preview. Can you check and then merge? Thx

2025-01-08 09:33 UTC, samuelpowell commented
Thanks @dboas this renders nicely now. We may need to synchronise the changeling following this update but I think we have neglected to maintain this on other commits so we can review prior to release.

2025-01-08 09:34 UTC, samuelpowell approved these changes

2025-01-08 09:34 UTC, merged