Make either 2D or 3D positions a requirement
fNIRS/snirf pull request #69
Opened 2021-08-31 01:06 UTC by rob-luke

Closes #65

This changes the specification to require either 2D or 3D positions, not just 2D.

2021-08-31 04:37 UTC, dsleiter commented
Good to hear this is being implemented!

To ensure internal consistency within the document, the "SNIRF data format summary" section should probably be updated as well. There isn't an existing notation for "one of" - one option that comes to mind is:  `*ⁿ` (with `*¹` for source positions and `*²` for detector positions)

> * `*ⁿ` in the last column indicates that at least one of the subfields in the subgroup identified by `n` required

But maybe there is another simpler notation.

2021-09-02 05:54 UTC, fangq requested changes
use `detectorPos2D` to quote SNIRF field names. 

also need to add a notation, say "**" or "+" in the summary table for the relevant fields

https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#snirf-data-format-summary

for some reason, I feel that this solution is a bit cumbersome for future validator's/parsers, but don't have a better suggestion at this point.

2021-09-02 21:27 UTC, fangq approved these changes
looks good, thanks

2021-09-02 21:27 UTC, merged

2021-09-02 23:50 UTC, rob-luke commented
Thanks for the feedback @dsleiter and @fangq